{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: fuel-ops-web }
spec:
  scaleTargetRef:
    apiVersion: {{ if eq .Values.webStrategy "rolling" }}apps/v1{{ else }}argoproj.io/v1alpha1{{ end }}
    kind: {{ if eq .Values.webStrategy "rolling" }}Deployment{{ else }}Rollout{{ end }}
    name: fuel-ops-web
  minReplicas: {{ .Values.autoscaling.min }}
  maxReplicas: {{ .Values.autoscaling.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: {{ .Values.autoscaling.cpu }} }
{{- end }}
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: { name: fuel-ops }
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service: { name: fuel-ops-api, port: { number: 4000 } }
          - path: /
            pathType: Prefix
            backend:
              service: { name: fuel-ops-web, port: { number: 3000 } }
{{- end }}
