"use client";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Badge, Card, ErrorBox, Loading } from "@/components/ui";
import { api } from "@/lib/api";
type Report={version:string;library:string;dataset:string;split:{trainEpisodes:number;validationEpisodes:number;testEpisodes:number;trainRows:number;validationRows:number;testRows:number;method:string};weights:Record<string,number>;metrics:{model:string;mae:number;rmse:number;r2:number;wape:number}[];stockout:{matrix:number[][];precision:number;recall:number;f1:number;accuracy:number;samples:number;definition:string};sample:{actual:number;predicted:number}[];intervalCoverage:number;limitations:string[]};
export default function MlEvidence(){
 const {data,error,isLoading}=useQuery({queryKey:['trained-model'],queryFn:()=>api<{available:boolean;error:string|null;version:string|null;report:Report|null}>('/forecast/trained-model')});
 if(isLoading)return <Loading/>;if(error)return <ErrorBox error={error}/>;
 const r=data?.report;if(!r)return <Card title="Trained forecasting"><p>Statistical fallback active: {data?.error}</p></Card>;
 const pct=(x:number)=>(x*100).toFixed(1)+'%';
 return <div className="space-y-4">
 <div><h1 className="text-xl font-semibold">Trained ML · evaluation evidence</h1><p className="text-sm text-muted">Random Forest + Extra Trees + Gradient Boosting · {r.library}</p></div>
 <Card title="Operational forecast"><div className="flex flex-wrap gap-2"><Badge tone={data?.available?'ok':'warn'}>{data?.available?'Trained artifact loaded':'Fallback active'}</Badge><Badge tone="info">{r.version}</Badge><Link className="text-accent underline" href="/forecast">Inspect live forecasts →</Link></div><p className="mt-2 text-sm">The API runs exported trained trees. The first 12 observations use the statistical fallback; trained forecasts then feed the existing stockout and allocation engines. Invalid inputs or unavailable artifacts fall back automatically.</p></Card>
 <Card title="Dataset and held-out evaluation"><p className="text-sm">{r.dataset}</p><p className="mt-2 text-sm">{r.split.trainRows.toLocaleString()} training rows / {r.split.validationRows.toLocaleString()} validation rows / {r.split.testRows.toLocaleString()} test rows across {r.split.trainEpisodes+r.split.validationEpisodes+r.split.testEpisodes} episodes.</p><p className="mt-1 text-xs text-muted">{r.split.method}</p><div className="mt-3 flex gap-4 text-sm"><a className="text-accent underline" href="/ml/evaluation.png" target="_blank">Open evaluation figure</a><a className="text-accent underline" href="/ml/evaluation.json" download>Download metrics JSON</a></div></Card>
 <div className="grid gap-4 lg:grid-cols-2"><Card title="Forecast error on held-out synthetic data"><div className="h-64"><ResponsiveContainer><BarChart data={r.metrics} layout="vertical" margin={{left:30,right:20}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="model" width={130} tick={{fontSize:11}}/><Tooltip/><Legend/><Bar isAnimationActive={false} dataKey="mae" name="MAE (L/tick)" fill="#38bdf8"/><Bar isAnimationActive={false} dataKey="rmse" name="RMSE (L/tick)" fill="#818cf8"/></BarChart></ResponsiveContainer></div></Card>
 <Card title="Actual versus ensemble prediction"><div className="h-64"><ResponsiveContainer><LineChart data={r.sample}><CartesianGrid strokeDasharray="3 3"/><XAxis/><YAxis/><Tooltip/><Legend/><Line isAnimationActive={false} dataKey="actual" stroke="#34d399" dot={false}/><Line isAnimationActive={false} dataKey="predicted" stroke="#38bdf8" dot={false}/></LineChart></ResponsiveContainer></div><p className="text-xs text-muted">Six consecutive held-out 6h forecast windows; litres per tick.</p></Card></div>
 <Card title="Regression metrics"><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr><th>Model</th><th>MAE (L)</th><th>RMSE (L)</th><th>R²</th><th>WAPE</th><th>Ensemble weight</th></tr></thead><tbody>{r.metrics.map(m=><tr key={m.model} className="border-t border-border"><td className="py-2">{m.model}</td><td>{m.mae.toFixed(2)}</td><td>{m.rmse.toFixed(2)}</td><td>{m.r2.toFixed(3)}</td><td>{pct(m.wape)}</td><td>{r.weights[m.model]!==undefined?pct(r.weights[m.model]):'—'}</td></tr>)}</tbody></table></div></Card>
 <div className="grid gap-4 lg:grid-cols-2"><Card title="Stockout confusion matrix (6 h)"><p className="mb-3 text-xs text-muted">{r.stockout.definition}</p><table className="w-full text-sm text-center"><thead><tr><th>Actual ↓ / predicted →</th><th>No stockout</th><th>Stockout</th></tr></thead><tbody>{r.stockout.matrix.map((row,i)=><tr key={i}><th>{i?'Stockout':'No stockout'}</th>{row.map((n,j)=><td key={j} className={`p-4 text-2xl font-semibold ${i===j?'bg-emerald-500/15':'bg-amber-500/15'}`}>{n}</td>)}</tr>)}</tbody></table><p className="mt-3 text-xs text-muted">{r.stockout.samples} held-out forecast windows.</p></Card><Card title="Stockout classification metrics"><dl className="grid grid-cols-2 gap-4">{(['precision','recall','f1','accuracy'] as const).map(k=><div key={k}><dt className="capitalize text-muted">{k}</dt><dd className="text-2xl font-semibold">{pct(r.stockout[k])}</dd></div>)}</dl><p className="mt-4 text-xs text-muted">Empirical demand interval coverage on test: {pct(r.intervalCoverage)}. Forecast confidence expresses synthetic validation reliability; it is not a probability that an LLM explanation is correct.</p></Card></div>
 <Card title="Scope of the evidence"><ul className="list-disc pl-4 text-sm space-y-1">{r.limitations.map(x=><li key={x}>{x}</li>)}</ul></Card>
 </div>;
}
